# .air.toml

root = "."
tmp_dir = ".air"

[build]
  bin = "./.air/main"
  cmd = "go build -o ./.air/main ./cmd/main.go"
  delay = 1000
  exclude_dir = [".air"]
  exclude_file = []
  exclude_regex = []
  exclude_unchanged = false
  follow_symlink = false
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = false